name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
