name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Install dependencies
      run: sudo apt-get install -y cmake gcc g++ curl libssl-dev libcurl4-openssl-dev

    - name: Build
      run: cmake -B build -S . && cmake --build build

    - name: Run tests
      run: cd build && ctest
