name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install compilers and cURL
        run: |
          sudo apt update
          sudo apt install -y cmake gcc g++ curl libssl-dev libcurl4-openssl-dev

      - name: Compile project with CLion
        run: |
          cd http_curl_wrapper
          clion.sh build --rebuild --force-all
