name: CMake Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v2

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build

    - name: Update README badge
      if: ${{ always() }}
      uses: peaceiris/actions-badges@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        readme_path: README.md
        badge_label: build
        badge_message: ${{ job.status }}
        color: ${{ job.status == 'success' && 'green' || 'red' }}
