name: CMake

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install compilers
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++

    - name: Install cURL
      run: |
        sudo apt-get install -y curl
        sudo apt-get install -y libssl-dev libcurl4-openssl-dev

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ./build/tst/http_curl_wrapper_tst
