name: CMake

on: [push, pull_request]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++ libcurl4-openssl-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg install curl:x64-windows
        .\vcpkg\vcpkg install gtest:x64-windows

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      run: cmake --build build --config Debug

    - name: Run tests
      run: .\build\tst\Debug\http_curl_wrapper_tst.exe
